airbrake/airbrake-js

- src/client.coffee
- src/notifier.coffee
- src/util/jsonify_notice.coffee
- test/unit/util/jsonify_notice_test.coffee
- test/unit/util/truncate_test.coffee
Should help to debug https://github.com/airbrake/airbrake-js/issues/125
> Better error message when notice can not be converted to JSON.

- src/reporters/xhr.coffee
- test/unit/reporters/xhr_test.coffee
With this change browser should not issue CORS preflight request when
posting data to Airbrake.
> Use old compatibility API that does not require Content-Type header.

- README.md
- examples/browserify/app.js
- examples/legacy/app.js
- examples/requirejs/app.js
- src/client.coffee
- test/unit/client_test.coffee
Changes:
- push is renamed to notify. push is still available, but is deprecated.
- setEnvironmentName, addContext, addEnvironment, addSession and addParams are deprecated in favor of filters.
> Cleanup API to be consistent with other notifiers.

- src/client.coffee
- src/reporters/compat.coffee
- src/reporters/jsonp.coffee
- test/unit/client_test.coffee
- test/unit/reporters/compat_test.coffee
@cadpntr this is an alternative way, e.g. to solve your issue you will need to pass reporter option:
```
var airbrake = new airbrakeJs.Client({projectId: 1, projectKey: 'abc', 'reporter': 'xhr'});
```
Replaces https://github.com/airbrake/airbrake-js/pull/167
> Add xhr and compat reporters.

- README.md
Airbrake-js is now available on cdnjs:
https://cdnjs.com/libraries/airbrake-js
Fixes #151, #35.
> Document CDN (cdnjs) usage

- README.md
I am using webpack.  `airbrakeJs.Client` does not exist, but `new airbrakeJs(...)` works well.
> add instructions for using with browserify/webpack/etc

- README.md
This typo causes a syntax error.
> Add a missing comma in the example usage

- package.json
Otherwise it fails on Circle with:
```
Error: Cannot find module 'coffee-script/register'
```
It passes locally for me and I could see the
`node_modules/coffee-script` directory. However on Circle this
dependency is missing (not sure why).
> package.json: depend on 'coffee-script' to fix builds

- README.md
These examples are useful, make it clear that they exist by linking to
them from the readme.
> Link to example from README

- webpack.config.js
Adds version info as a comment on build. Example: `/*! Airbrake JS v0.9.0 */` would be added as the first line of the files in `dist/`.
> Add banner plugin to show version info

- examples/angular-2/README.md
I plan to pull this README.md into airbrake-docs so we only need to manage the configuration for Angular 2 instructions in a single location.
I've made minor additions to the copy and modifications to header sizes to better fit into the docs site.
I updated the code blocks to use `ts` instead since the docs site does not perform correct highlighting with `TypeScript` specified.
More details: https://github.com/airbrake/airbrake-docs/pull/232
> Update the angular 2 doc

- examples/react/README.md
I'm going to fetch this readme for use in airbrake-docs.
I've decreased the size of the header to better match what we use on the
docs site and added a bit more copy explaining the setup.
> Update the React readme

- examples/vuejs/README.md
This is a minor update preparing the Vue.js readme for use in airbrake-docs.
- Decrease the header size for consistency with airbrake-docs
- Increase the verbosity of the configuration instructions
> Update the Vue.js readme

- src/client.ts
The native event-handler in Chrome puts the Reason and Promise in the root event, but Bluebird attaches them to the event detail.
https://developer.mozilla.org/en-US/docs/Web/Events/unhandledrejection
http://bluebirdjs.com/docs/api/error-management-configuration.html
> Handle native or bluebird Promise rejections

- examples/nodejs/app.js
Hi, without this fix we catch an error:
`error TypeError: requestWrapper is not a function`
in node_modules/airbrake-js/dist/client.js:2530:9
> Fix nodejs example

- README.md
Replaces the **Source maps** section with links to both private and public docs pages:
- https://airbrake.io/docs/features/public-sourcemaps/
- https://airbrake.io/docs/features/private-sourcemaps/
> Add links to our docs site for source maps

- src/instrumentation/dom.ts
This PR fixes an error in airbrake breadcrumb element path
Example error: `Click on<TypeError: e.className.split is not a function>`
The root cause of this issue is because not all `className` property of DOM elements are strings. Those who don't have no `split` method (for example, `svg` element and their children, with type `SVGAnimatedString` instead of `string`).
You can see all element with issue in a page using the following snippet: `Array.from(document.body.getElementsByTagName("*")).filter(elm => elm.className).filter(elm => typeof elm.className !== 'string')`
> Fix error message in target path when className not a string

- src/client.ts
- test/unit/client_test.ts
If no reason is specified in the rejection, the client would throw
`Error: Uncaught TypeError: Cannot read property 'reason' of undefined`.
This adds a guard to reading the `.detail` property.
We are seeing this error a lot in our airbrake logs, which is how we caught this :)
> Fix handling unhandled rejections without reasons

- src/instrumentation/dom.ts
On older browsers and IE11 `Array.from` does not exist and causes an error.
> fixed <TypeError: Object doesn't support property or method 'from'>

- packages/browser/README.md
- packages/browser/examples/angular-2/README.md
- packages/browser/examples/angular/README.md
Clarify which example is AngularJS (AKA: Angular version 1) and which example is Angular (AKA: Angular version 2 and up).
> Clarify AngularJS vs Angular example apps

- packages/browser/examples/angular/README.md
The example given for `Angularjs` had a case-sensitivity typo that occurred to me while checking the library with my application.
The correct names for the params are `projectId` and `projectKey`.
> Fix AngularJS Example Typo in README.md

- packages/browser/examples/react/README.md
The library is `@airbrake/browser` not `@airbrake/notifier`.  This was reported by a user via support.
> Fix import statement

- packages/node/examples/express/README.md
Add steps for users to follow. This formats the Express example readme more like a guide or tutorial making it easier for users to add Airbrake to their app. Steps include how to adapt the example and how to run the example app locally.
Paired with @mmcdaris on this 🍐 👍
> Add steps to the Express example

- packages/browser/tests/processor/stacktracejs.test.js
Node.js v10 is returning the function name as `'Object.beforeEach'` rather than `'Object.<anonymous>'`. By moving the code that throws the error out of an anonymous function and into a named function, we can avoid this ambiguity.
> Fix stacktrace test for node v10

- packages/browser/examples/react/README.md
We are using `Notifier` instead of `Airbrake.Notifier` since
https://github.com/airbrake/airbrake-js/commit/7f01da95503fc0157299e52e7d34b98956361b5f#diff-e859334626963a0e732c1606a9531dd6.
> Update React installation instructions

- packages/browser/package.json
These are no longer being used.
> Remove ts-loader and tslint-loader

- packages/browser/src/filter/filter.ts
Fixes this error:
```
Module '"/airbrake-js/packages/browser/src/notice"' has no default export. Did you mean to use 'import { INotice } from "/airbrake-js/packages/browser/src/notice"' instead?
```
> Fix import of INotice

- .github/workflows/ci.yml
- lerna.json
- package.json
- yarn.lock
Configures lerna to defer to yarn to handle dependency management. This allows us to make use of yarn's native mono-repo capabilities alongside lerna's powerful utility commands and publishing features.
https://classic.yarnpkg.com/en/docs/workspaces/
> Enable yarn workspaces

- packages/browser/dist/airbrake.d.ts
- packages/browser/src/options.ts
- packages/node/src/notifier.ts
- packages/node/tests/notifier.test.js
Allows users to disable the automatic instrumentation of various performance stats.
For https://github.com/airbrake/airbrake-js/issues/641
> Add config option to disable performance stats

- packages/browser/src/base_notifier.ts
- packages/browser/src/version.ts
- packages/node/src/filter/node.ts
- packages/node/src/version.ts
Adds `version.ts` to both packages to allow us to set the notifier properties when reporting to Airbrake.
> Add version constants

- packages/node/src/instrumentation/express.ts
The route path can be a string, regex, or array, so it needs to be stringified before attempting to report it to Airbrake.
Fixes #668
> Fix Express route stat reporting

- packages/browser/package.json
- yarn.lock
tslib is a peer dependency of @rollup/plugin-typescript.
> browser: add tslib to devDependencies

- .github/workflows/ci.yml
- package.json
- packages/browser/package.json
- packages/node/package.json
Makes use of `runInBand` option, which is recommended to use in situations with limited resources.
https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server
Fixes #663
> Add script for CI test runs

- packages/browser/examples/react/README.md
The general React library which is needed in this example. To use this example in your app, you also need to export the newly added component. This update adds those two to make the example easier to follow.
> Add import and export for React example

- packages/node/src/instrumentation/express.ts
When reporting the current URL, we should use `originalUrl` over `path`. `path` does not include the mount point while `originalUrl` does.
https://expressjs.com/en/4x/api.html#req.path
https://expressjs.com/en/4x/api.html#req.originalUrl
> Use req.originalUrl instead of req.path

- packages/browser/src/notifier.ts
When the notifier is loaded via server-side rendering, we need to return early because `window` is not available.
Fixes https://github.com/airbrake/airbrake-js/issues/678
> browser: add guard for window being undefined

- packages/browser/src/notifier.ts
Can cause Typescript build errors in Node.js projects.
> Remove onUnhandledrejection parameter type

- packages/browser/src/base_notifier.ts
- packages/browser/src/filter/performance_filter.ts
- packages/node/README.md
- packages/node/tests/routes.test.js
Allows users to stop metrics from being reported to Airbrake.
Closes https://github.com/airbrake/airbrake-js/issues/688
> Add performance filtering

- packages/browser/src/notifier.ts
To distinguish error source, I wanna add `context` information when error was caught by `unhandledrejection` event.
It's similar as errors from `window.onerror` have `windowError` context as below:
https://github.com/airbrake/airbrake-js/blob/ec02287618015aa318493cc7de196a5738cb5a41/packages/browser/src/notifier.ts#L144-L182
---
In the case of `unhandledrejection`, the parameter of `notify` method can be either object or other types.
https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent/reason
`base_notifier` checks it here:
https://github.com/airbrake/airbrake-js/blob/ec02287618015aa318493cc7de196a5738cb5a41/packages/browser/src/base_notifier.ts#L114-L116
So I added this check in advance before calling `notify` method. (Though there may be more good way)
I hope this pull …
> Add unhandledRejection info to context

- README.md
- packages/browser/README.md
- packages/node/README.md
Airbrake has a new logo. This replaces the old Arthur logos (which looked to be a broken link) with this new logo:
> Add new logo

- packages/node/src/notifier.ts
To avoid async_hooks being used by default even when performanceStats is disabled because it comes with a performance overhead.
Fixes:  https://github.com/airbrake/airbrake-js/issues/892
> Conditionally initialize ScopeManager

- CHANGELOG.md
- packages/browser/src/base_notifier.ts
- packages/browser/src/options.ts
Deprecated in 037352ac3a415a9dd3b6c1b30af916535d5eab12.
It's time to remove it.
> Remove deprecated `keysBlacklist` option

- packages/node/src/notifier.ts
Specified file extension in instrumentation require to prevent webpack from attempting to load typescript definition and map files.
Closes ##935
> Specify file extension in notifier.ts

- CHANGELOG.md
- packages/browser/src/remote_settings.ts
Fixes #1000
(TypeError: undefined is not an object (evaluating 'e.searchParams.append'))
Old browsers such as IE don't support `Object.entries`. Therefore, all the calls
to that property would fail... every 10 minutes :-(
`Object.entries` support:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#browser_compatibility
> remote_settings: fix TypeError when calling Object.entries

- CHANGELOG.md
- packages/browser/src/routes.ts
In JavaScript we cannot reference array elements by providing a negative
index (unlike in Ruby or Python). The code incorrectly assumed that this works.
As result, the library could never send any response types to Airbrake.
The fix is simple: we reference the last element of the array the way JavaScript
wants.
> browser/src/routes: correctly index last element in responseType

- .github/workflows/ci.yml
We drop Node 12.x because it's not supported anymore. Some of our deps require 14+
> Test against Node 14.x, 16.x and 18.x

- packages/browser/package.json
- packages/node/package.json
In https://github.com/airbrake/airbrake-js/pull/1141 I mistakenly added that flag thinking that it clears cache AND runs tests. After reading the docs more carefully, I realized I was wrong.
It's a miracle nothing broke.
> package.json: don't pass clearCache to Jest

- CHANGELOG.md
- packages/browser/src/jsonify_notice.ts
- packages/browser/tests/jsonify_notice.test.js
Fixes https://github.com/airbrake/airbrake-js/issues/1301 (Using blocklist with "name" filters out notifier name)
Just like in airbrake-ruby, we must not filter out service information, such as notifier name and version.
> browser/src/jsonify_notice: don't filter `context`

- packages/browser/README.md
Fixes https://github.com/airbrake/airbrake-js/issues/737 (missing doc for instrumentation options (onerror in particular))
> browser/README: document InstrumentationOptions

- packages/browser/src/base_notifier.ts
We don't really need to build the notice object in order to perform the
'object' check.
> browser/base_notifier: check for object early in 'notify'

- packages/browser/src/base_notifier.ts
This check exists because we want to see if the 'error' key was passed when 'err' is an object. In https://github.com/airbrake/airbrake-js/issues/829 we want to add support for "falsey" values, which cannot be reported as of now. This check prevented "undefined" values, that's why we modified it to check for the property's existence, instead of its value.
> browser/base_notifier: check for 'error' in 'err' properly

- CHANGELOG.md
- packages/browser/src/base_notifier.ts
- packages/browser/tests/client.test.js
Fixes https://github.com/airbrake/airbrake-js/issues/829
("Uncaught undefined" and "Uncaught false" is not showing in console)
> browser/base_notifier: allow reporting of falsey errors
