src/client.coffee, src/internal/promise.coffee, src/reporters/jsonp.coffee, src/reporters/xhr.coffee, test/unit/client_test.coffee, test/unit/internal/promise_test.coffee
Fixes https://github.com/airbrake/airbrake-js/issues/131
=> Change push to return promise that is resolved with notice id.

LICENSE, README.md
Change Rackspace mention to Airbrake
=> Remove Rackspace mention

src/client.coffee, test/unit/client_test.coffee
=> Set context.rootDirectory.

src/client.coffee
Allow host option to be set via constructor function
=> Allow host option to be set via constructor function

bower.json
Looks like main file now resides in the `dist` folder
=> Fix main file path

README.md
The code raised an error in strict mode.
=> fixed undeclared var in sample Angular integration

src/client.coffee
Fixes https://github.com/airbrake/airbrake-js/issues/198
=> Add onerror option to disable window.onerror setup.

src/processors/stack.coffee, test/unit/processors/stack_test.coffee
Hopefully fixes https://github.com/airbrake/airbrake-js/issues/197
=> Make sure message is a string.

examples/rails/README.md
A minor improvement to make the Rails example more accurate and useful.
=> Improve Rails example usage

examples/react-native/README.md
Thanks to @padupuy in #222 for the helpful information.
=> Add a React Native configuration example

README.md, examples/angular/README.md
This is more consistent with existing examples.
=> Move Angular 1 config example for consistency

examples/angular-2/README.md
Based on the discussion in #209.
=> Add an Angular 2 TypeScript configuration example

examples/angular/README.md
I already saw a question from 2 different users about where `config` dependency comes from.
=> Remove config dependency.

package.json, src/processors/stacktracejs.coffee, test/unit/processors/stacktracejs_test.coffee
Updates https://github.com/airbrake/airbrake-js/issues/220
=> Add stacktracejs backend.

src/client.coffee
Fixes https://github.com/airbrake/airbrake-js/issues/220
=> Enable stacktracejs by default.

src/client.ts, test/unit/client_test.coffee
Reported notice contains last 10 log messages (if any).
=> Add console instrumentation.

src/client.ts, src/instrumentation/dom.ts, test/unit/client_test.coffee
Updates https://github.com/airbrake/airbrake-js/issues/218. WIP - more work is required to close the issue.
=> Record clicks on DOM elements.

src/client.ts, src/reporter/compat.ts, src/reporter/xhr.ts
Updates https://github.com/airbrake/airbrake-js/issues/218
=> Add XHR instrumentation.

src/client.ts, src/processor/stacktracejs.ts, test/unit/processor/stacktracejs_test.ts
Fixes https://github.com/airbrake/airbrake-js/issues/285
=> Always report text message even without a backtrace.

src/client.ts, test/unit/client_test.ts
Fixes https://github.com/airbrake/airbrake-js/issues/204
=> Queue errors when offline and report when online.

README.md, src/instrumentation/historian.ts
Updates https://github.com/airbrake/airbrake-js/issues/312
=> src/instrumentation: always setup onerror handler

src/client.ts, src/filter/debounce.ts, test/unit/client_test.ts
Fixes https://github.com/airbrake/airbrake-js/issues/321
=> Debounce notice notify

src/client.ts, src/filter/ignore.ts, src/processor/stacktracejs.ts, test/unit/client_test.ts
Fixes https://github.com/airbrake/airbrake-js/issues/315
=> Ignore errors in anonymous files

README.md, src/client.ts, src/reporter/reporter.ts, test/unit/client_test.ts
Fixes https://github.com/airbrake/airbrake-js/issues/339
=> Add ignoreWindowError option.

src/filter/debounce.ts, src/jsonify_notice.ts, src/notice.ts, test/unit/jsonify_notice_test.ts
Fixes https://github.com/airbrake/airbrake-js/issues/341
=> Use jsonifyNotice in debounce filter

src/filter/debounce.ts, src/jsonify_notice.ts, test/unit/jsonify_notice_test.ts
Closes https://github.com/airbrake/airbrake-js/issues/344
=> Compare notice.errors in debounce filter

README.md
Fixes https://github.com/airbrake/airbrake-docs/issues/151
=> readme: send text message

src/filter/debounce.ts
Fixes https://github.com/airbrake/airbrake-js/issues/357
=> Don't use window.setTimeout

examples/angular-2/README.md
Fixes https://github.com/airbrake/airbrake-js/issues/360
=> Update Angular 2 example

README.md
https://github.com/airbrake/airbrake-js/issues/363
=> Added a note about request dependency for issue #363

src/instrumentation/historian.ts
Fixes https://github.com/airbrake/airbrake-js/issues/374
=> Check p.on

src/client.ts, src/instrumentation/historian.ts
Fixes https://github.com/airbrake/airbrake-js/issues/382
=> Check if addEventListener is available

src/jsonify_notice.ts, src/notice.ts, test/unit/jsonify_notice_test.ts
Fixes https://github.com/airbrake/airbrake-js/issues/381
=> Truncate notice.errors too with minimal level

src/instrumentation/historian.ts
Fixes https://github.com/airbrake/airbrake-js/issues/387
=> src/instrumentation: remove document.addEventListener alias

src/promise.ts, test/unit/promise_test.ts
Updates https://github.com/airbrake/airbrake-js/pull/393
=> Complete Promise polyfill with finally and all

src/instrumentation/historian.ts, src/promise.ts
Replaces https://github.com/airbrake/airbrake-js/pull/393
=> src: exit on uncaught error in Node.js

src/instrumentation/historian.ts
Fixes https://github.com/airbrake/airbrake-js/issues/396
=> src/instrumentation: check if document is available

src/promise.ts, test/unit/promise_test.ts
Fixes https://github.com/airbrake/airbrake-js/pull/402
=> Allow Promise to be resolved with null and false

examples/rails/README.md
Decrease the size of the header in the rails README.md for use in
airbrake-docs.
=> Update rails readme header

src/reporter/fetch.ts, src/reporter/node.ts, src/reporter/xhr.ts
Fixes https://github.com/airbrake/airbrake-js/issues/414
=> Catch JSON parsing exceptions

src/client.ts, src/historian.ts, test/unit/client_test.ts
Fixes https://github.com/airbrake/airbrake-js/issues/379
=> Add test for errors thrown in Promises

dist/client.d.ts, package.json
Fixes https://github.com/airbrake/airbrake-js/issues/348
=> Add manually written typescript definitions

src/historian.ts
Fixes https://github.com/airbrake/airbrake-js/issues/425
=> Don't report unhandled rejections from airbrake-js

README.md, src/client.ts, src/reporter/node.ts, src/reporter/reporter.ts
Fixes https://github.com/airbrake/airbrake-js/issues/424
=> Allow specifying request wrapper via options

examples/angular/README.md
Uses style consistent with [AngularJS style guide](https://github.com/johnpapa/angular-styleguide/tree/7019503f2c8a637d1a70f5719cb17b9669653565/a1) for AngularJS code example.
=> Use consistent style for AngularJS code example

karma.conf.js, src/filter/node.ts, src/historian.ts, src/reporter/node.ts, webpack.config.js
Fixes https://github.com/airbrake/airbrake-js/issues/438
=> Remove eval usage

test/unit/client_test.ts, test/unit/historian_test.ts, test/unit/sinon_chai.ts, tsconfig.json
Fixes https://github.com/airbrake/airbrake-js/issues/441
=> typescript: enable esModuleInterop

README.md, src/client.ts, src/historian.ts, test/unit/client_test.ts
Fixes https://github.com/airbrake/airbrake-js/issues/447
=> Add opts.environment and opts.unwrapConsole

webpack.config.js
Fixes https://github.com/airbrake/airbrake-js/issues/450
=> Disable nodeEnv optimization

src/historian.ts
Fixes https://github.com/airbrake/airbrake-js/issues/455
On Node.js following app
```js
const AirbrakeClient = require('airbrake-js');
async function test() {
Promise.reject(new Error('test'));
}
test();
```
produces
```
unhandled rejection Error: test
at test (/home/vmihailenco/workspace/airbrake-js/examples/nodejs/test.js:4:18)
at Object.<anonymous> (/home/vmihailenco/workspace/airbrake-js/examples/nodejs/test.js:6:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3
```
which is close enough to original Node.js behavior
=> Exit on unhandled rejection to mimic Node.js behavior

src/reporter/node.ts
Updates https://github.com/airbrake/airbrake-js/pull/459
=> src/reporter: log helpful message when request package is not installed

src/historian.ts
Fixes https://github.com/airbrake/airbrake-js/issues/466
=> Fix unhandled rejection when instrumenting fetch

src/instrumentation/dom.ts
Follow up for https://github.com/airbrake/airbrake-js/pull/479
@pandaiolo please take a look if you have a free minute
=> Handle SVGAnimatedString as class name

src/client.ts, src/filter/node.ts, src/historian.ts, src/instrumentation/dom.ts
Updates https://github.com/airbrake/airbrake-js/issues/478
=> Add HistorianOptions

src/instrumentation/express.ts, src/routes.ts
Fixes https://github.com/airbrake/airbrake-js/issues/493
=> Use process.hrtime on Node.js

package.json, src/http_req/fetch.ts, webpack.config.js
Fixes https://github.com/airbrake/airbrake-js/issues/490
=> Use cross-fetch

src/client.ts, src/filter/node.ts, src/historian.ts, src/jsonify_notice.ts, src/routes.ts, test/unit/jsonify_notice_test.ts
Replaces https://github.com/airbrake/airbrake-js/pull/492
=> Safe iteration

package.json
Updates https://github.com/airbrake/airbrake-js/issues/502
=> Use peer dependency

src/instrumentation/dom.ts
Fixes https://github.com/airbrake/airbrake-js/issues/518
=> Fix undefined toString

src/client.ts
Fixes https://github.com/airbrake/airbrake-js/issues/517
=> Check options.reporter

examples/rails/README.md
rails-assets.org is no longer properly maintained. Instead, we now provide examples using the asset pipeline or Webpacker.
For https://github.com/airbrake/airbrake-js/issues/507
=> Update Rails example

dist/client.d.ts
=> Update Client type definitions

dist/client.d.ts
Fixes https://github.com/airbrake/airbrake-js/issues/527
=> Update typescript definitions

README.md
Fixes https://github.com/airbrake/airbrake-js/issues/530
=> Document instrumentation.console

src/instrumentation/express.ts, src/routes.ts
Fixes https://github.com/airbrake/airbrake-js/issues/542
=> Remove hrtime

src/historian.ts, test/unit/historian_test.ts
Replaces https://github.com/airbrake/airbrake-js/pull/541
=> Use RequestInfo.method

src/client.ts
Fixes https://github.com/airbrake/airbrake-js/issues/547
=> Disable route stats without tdigest

package.json, src/index.ts
Fixes https://github.com/airbrake/airbrake-js/issues/502
=> Include src into package

test/unit/client_test.ts, tests/truncate.test.js
Fixes #550.
I rewrote tests.
You can run the test by using command: `npm run test`
=> Rewrite truncate tests

tests/jsonify_notice.test.js
=> Convert jsonify notice tests to jest

packages/browser/src/base_notifier.ts, packages/node/rollup.config.js, packages/node/src/instrumentation/debug.ts
Closes https://github.com/airbrake/airbrake-js/issues/386
=> Add debug integration

packages/node/package.json, packages/node/rollup.config.js
Fixes https://github.com/airbrake/airbrake-js/issues/590
=> airbrake/node: add esm build

packages/browser/src/base_notifier.ts, packages/node/src/notifier.ts
Updates https://github.com/airbrake/airbrake-js/issues/560
=> Add ability to flush pending errors

packages/node/src/instrumentation/pg.ts
Fixes https://github.com/airbrake/airbrake-js/issues/607
=> Add missing catch to the promise handling

packages/browser/src/instrumentation/location.ts
Fixes https://github.com/airbrake/airbrake-js/issues/612
=> Protect against document.location EQ null

packages/browser/src/instrumentation/dom.ts
Fixes https://github.com/airbrake/airbrake-js/issues/616
=> Handle Permission denied to access property error

.travis.yml, package.json, scripts/test.sh
Leverages lerna to run all tests and configures Travis to run against more node versions.
=> Set up lerna to run tests from project root

packages/node/examples/express/README.md, packages/node/examples/express/app.js, packages/node/examples/express/package.json, packages/node/examples/nodejs/README.md, packages/node/examples/nodejs/app.js, packages/node/examples/nodejs/package.json
Updates the instructions and example apps for node
=> Update examples for node package

packages/browser/examples/angular-2/README.md
This adds a comment with the file path in each code block in Angular
installation instructions. This is mainly to better guide our users.
=> Update Angular installation instructions

packages/browser/package.json, yarn.lock
Adds these packages as dependencies so consumers of our package don't need to manually install them.
=> Add request and promise-polyfill types

packages/browser/package.json, packages/browser/rollup.config.js, yarn.lock
Not used since e30c020ba2a7636e56fc5ae64f8dc4dfb38222b0.
=> Remove rollup-plugin-replace

CONTRIBUTING.md
Basic set up instructions. Additional guidelines and documentation can be added later.
=> Add initial contributing doc

packages/browser/examples/browserify/README.md, packages/browser/examples/browserify/app.js, packages/browser/examples/browserify/index.html, packages/browser/examples/browserify/package.json, packages/browser/examples/legacy/README.md, packages/browser/examples/legacy/app.js, packages/browser/examples/legacy/index.html, packages/browser/examples/legacy/package.json, packages/browser/examples/rails/README.md, packages/browser/examples/react/README.md, packages/browser/examples/redux/README.md, packages/browser/examples/vuejs/README.md, packages/node/examples/express/README.md, packages/node/examples/express/app.js
=> Update browser examples

CHANGELOG.md
Should have been included in edf5d47ded92337632aa6618472cf7518d3968d1.
=> Add release date to changelog

package.json, packages/browser/package.json, packages/node/package.json, yarn.lock
Useful when debugging apps locally.
=> Add scripts to automatically rebuild on changes

packages/browser/package.json, packages/browser/tsconfig.cjs.json, packages/browser/tsconfig.esm.json, packages/browser/tsconfig.json, packages/browser/tsconfig.umd.json, packages/node/package.json, packages/node/tsconfig.cjs.json, packages/node/tsconfig.esm.json, packages/node/tsconfig.json, tsconfig.esm.json, tsconfig.json
Some minor changes to improve development.
=> Tweak tsconfig setup

CHANGELOG.md, lerna.json, packages/browser/package.json, packages/browser/src/version.ts, packages/node/examples/express/package.json, packages/node/examples/nodejs/package.json, packages/node/package.json, packages/node/src/version.ts
Closes https://github.com/airbrake/airbrake-js/issues/699
=> Release v1.1.3

packages/browser/README.md, packages/node/README.md
Fixes https://github.com/airbrake/airbrake-js/issues/731
=> Fix README errors

CHANGELOG.md, packages/browser/README.md, packages/browser/src/base_notifier.ts, packages/browser/src/jsonify_notice.ts, packages/browser/src/options.ts, packages/browser/tests/client.test.js, packages/browser/tests/truncate.test.js, packages/node/README.md
=> Change keysBlacklist to keysBlocklist

packages/browser/src/notifier.ts
Added the ability to disable console tracking via instrumentation options for any environments.
=> Allow to disable console tracking for production

CHANGELOG.md, packages/browser/src/notifier.ts, packages/browser/src/options.ts
Deprecated in c0c0df79cbd2de408b74f5c8d9250e3bc8905e2c.
It's time to remove it.
=> Remove deprecated 'ignoreWindowError'

packages/node/package.json
Closes https://github.com/airbrake/airbrake-js/issues/745
=> Specify which versions of node are supported

CHANGELOG.md, packages/browser/README.md, packages/browser/src/jsonify_notice.ts, packages/browser/tests/jsonify_notice.test.js
Fixes https://github.com/airbrake/airbrake-js/issues/784 (add keysAllowlist option)
=> browser/src/jsonify_notice: add the keysAllowlist option

CHANGELOG.md, packages/browser/README.md, packages/browser/src/instrumentation/unhandledrejection.ts, packages/browser/src/notifier.ts, packages/browser/src/options.ts
Fixes #915
(Allow disabling handling of unhandledrejection)
=> [b] notifier: factor out unhandledrejection into an option
